Add Article Remote Source OAuth
fujitake/vantiq-related pull request #109
Opened 2022-10-03 07:15 UTC by shunsonohara

ver1.34 で導入された `Remote Source`でOAuth2.0 の認可フローで更新トークンを利用する機能の設定方法と検証の記事を追加

2022-10-03 07:16 UTC, shunsonohara commented
@MasanoriKono 
OAuthの記事を追加しました。レビューお願いします。

2022-10-03 08:04 UTC, MasanoriKono commented
@shunsonohara   以下の点を疑問に思いました。

- API Key + Secretというのは OAuth 1.0なので、この記事において扱うべきでしょうか。
- Refresh Tokenによるトークン取得をVantiqがサポートしているのはわかるが、Refresh Tokenはアプリの中で取得して揮発的なもの（メモリ上でのみ一時的に保持）されるものだと思うので、それを取得してVantiq Sourceに設定するという運用自体危険なのでは。

間違っていたらすみません。

2022-10-03 09:10 UTC, shunsonohara commented
> * API Key + Secretというのは OAuth 1.0なので、この記事において扱うべきでしょうか。

今回利用しているTwitter APIの仕様と理解してました。
https://developer.twitter.com/ja/docs/authentication/oauth-2-0/application-only
最初GoogleのAPIでやっていたのですがGoogleのAPIがClient Credential flowをサポートしていなくて…

> * Refresh Tokenによるトークン取得をVantiqがサポートしているのはわかるが、Refresh Tokenはアプリの中で取得して揮発的なもの（メモリ上でのみ一時的に保持）されるものだと思うので、それを取得してVantiq Sourceに設定するという運用自体危険なのでは。

現状では Propertiesに記載するしかないと認識してます。Secretsを参照できないか、Aha!に起票しています。
https://vantiq.aha.io/ideas/ideas/CP-I-324

2022-10-05 23:52 UTC, MasanoriKono commented on vantiq-apps-development/docs/jp/remote_source_oauth.md
> +[Twitter Developer Apps](https://developer.twitter.com/en/docs/apps/overview)
```suggestion
- [Twitter Developer Apps](https://developer.twitter.com/en/docs/apps/overview)
```

2022-10-05 23:52 UTC, MasanoriKono commented on vantiq-apps-development/docs/jp/remote_source_oauth.md
> +[OAuth 2.0](https://developer.twitter.com/en/docs/authentication/oauth-2-0)
```suggestion
- [OAuth 2.0](https://developer.twitter.com/en/docs/authentication/oauth-2-0)
```

2022-10-05 23:58 UTC, MasanoriKono commented on vantiq-apps-development/docs/jp/remote_source_oauth.md
> +[こちら](https://developer.twitter.com/en/docs/authentication/oauth-2-0/user-access-token) を参照し、アクセス トークンとリフレッシュ トークンをします。この手順で取得したリフレッシュトークンを後で利用します。
```suggestion
[こちら](https://developer.twitter.com/en/docs/authentication/oauth-2-0/user-access-token)  のStep 1 ~ 3を参照し、アクセス トークンとリフレッシュ トークンを取得します。この手順で取得したリフレッシュトークンを後で利用します。
```

2022-10-06 00:02 UTC, MasanoriKono commented on vantiq-apps-development/docs/jp/remote_source_oauth.md
> +期限の切れたアクセストークンを手動で更新するのではなく、有効なアクセストークンを再取得するための専用のSourceを作成することができるようになりました。これが `OAuth Source` です。
どこかに OAuth SourceのReferenceへのリンクを追加するべき。
https://dev.vantiq.co.jp/docs/system/sources/remote/index.html#fetching-access-tokens-on-demand

2022-10-06 00:11 UTC, MasanoriKono commented on vantiq-apps-development/docs/jp/remote_source_oauth.md
> +Remote Source に、OAuth Sourceからアクセストークンを取得するように設定すると、以下の流れでアクセストークンを取得し、Remote Source でAPIリクエストを行います。
2つの Source を用いることをどこかで説明を追加したほうがよい。
- OAuthサーバーのエンドポイントを定義する Source
- リソースサーバーのエンドポイントを定義する Source (本体）

2022-10-06 00:12 UTC, MasanoriKono commented on vantiq-apps-development/docs/jp/remote_source_oauth.md
> +必要な情報は以下の通りです。
この中で本記事の OAuthに関わるのは Client ID と Client Secret だけですよね？

2022-10-06 00:13 UTC, MasanoriKono requested changes
確認お願いします。

2022-10-06 07:16 UTC, shunsonohara commented on vantiq-apps-development/docs/jp/remote_source_oauth.md
> +必要な情報は以下の通りです。
https://developer.twitter.com/en/docs/authentication/oauth-2-0/application-only
TwitterのClient Credential Grant ではClient ID/Secret ではなく、Consumer Keys(API Key and Secret)を使用することになっています。Beare Tokenは不要ですね。削除します。

2022-10-06 07:26 UTC, shunsonohara reviewed
@MasanoriKono 
指摘事項の対応を行いました。

2022-10-06 07:26 UTC, shunsonohara commented on vantiq-apps-development/docs/jp/remote_source_oauth.md
> +
リファレンスへのリンクを追加

2022-10-06 07:26 UTC, shunsonohara commented on vantiq-apps-development/docs/jp/remote_source_oauth.md
> +- 実際に利用するRESTサービスのエンドポイントを定義する Remote Source (本体）
Sourceを2つ作成する必要があることを明記

2022-10-06 08:45 UTC, MasanoriKono approved these changes

2022-10-06 08:45 UTC, MasanoriKono commented
LGTM

2022-10-06 08:45 UTC, merged