shibata added English-version file of the difference after February 10
fujitake/vantiq-related pull request #110
Opened 2022-10-05 01:46 UTC by MeguShibata

2022-10-11 13:03 UTC, MasanoriKono commented on vantiq-apps-development/vantiq-resources-introduction/docs/eng/hands-on-lab.md
> +- Vantiq user registration should be completed.
```suggestion
- Vantiq user registration should have been completed.
```

2022-10-11 13:14 UTC, MasanoriKono commented on vantiq-cloud-infra-operations/terraform_aws/readme_en.md
> +  - The Worker Node of the Managed Node Group is only allowed to use SSH from the Bastion host.
```suggestion
  - The Worker Node of the Managed Node Group is only accessible via SSH from the Bastion host.    
```

2022-10-11 13:25 UTC, MasanoriKono commented on vantiq-external-services-integration/docs/en/vantiq-apigw.md
> +Vantiq cannot directly collaborate with services in the followings, so utilize the API Gateway.
```suggestion
In the following cases, Vantiq cannot directly connect with services in the followings, so API Gateway is configured.
```

2022-10-11 13:27 UTC, MasanoriKono commented on vantiq-external-services-integration/docs/en/vantiq-apigw.md
> +- Except for protocols supported by Vantiq (REST, WebSocket, MQTT, AMQP, Kafka, SMTP and so on) require a connection.
```suggestion
- Protocols other than those supported by Vantiq (REST, WebSocket, MQTT, AMQP, Kafka, SMTP, and so on) are required.   
```

2022-10-11 13:29 UTC, MasanoriKono commented on vantiq-external-services-integration/docs/en/vantiq-apigw.md
> +### Loosely Coupled Devices and Vantiq
```suggestion
### Keep the devices and Vantiq loosely coupled
```

2022-10-11 13:29 UTC, MasanoriKono commented on vantiq-external-services-integration/docs/en/vantiq-apigw.md
> +e.g）Devices are difficult to update once installed (tokens, URLs, etc.). On the other hand, endpoints on the Vantiq side have the possibility to change. API Gateway makes the API layer abstract and c
```suggestion
e.g.）Devices are difficult to update once installed (tokens, URLs, etc.). On the other hand, endpoints on the Vantiq side can change. API Gateway makes the API layer abstract and centrally manages security.  
```

2022-10-11 13:30 UTC, MasanoriKono commented on vantiq-external-services-integration/docs/en/vantiq-apigw.md
> +Convert and pass data in formats not supported by Vantiq.  e.g）
```suggestion
Convert and pass data whose format is not supported by Vantiq.  e.g.） 
```

2022-10-11 13:33 UTC, MasanoriKono commented on vantiq-external-services-integration/docs/en/vantiq-aws-iotcore.md
> +- Transmission of properties (Control Support)
```suggestion
- Transmit properties (Control Signal)    

```

2022-10-11 13:35 UTC, MasanoriKono commented on vantiq-external-services-integration/docs/en/vantiq-aws-iotcore.md
> +In this document, describe how to do the following from Vantiq's Procedures.
```suggestion
This document describes how to do the following from Vantiq's Procedures.  

```

2022-10-11 13:35 UTC, MasanoriKono commented on vantiq-external-services-integration/docs/en/vantiq-aws-iotcore.md
> +- Retrieve properties (Control Support, Device Shadow) of "Things"
```suggestion
- Retrieve properties (Control Signal, Device Shadow) of "Things"  

```

2022-10-11 13:37 UTC, MasanoriKono commented on vantiq-external-services-integration/docs/en/vantiq-aws-iotcore.md
> +## Creating "Things" for Vantiq assignment
```suggestion
## Creating "Things" to be assigned to Vantiq 

```

2022-10-11 13:38 UTC, MasanoriKono commented on vantiq-external-services-integration/docs/en/vantiq-aws-iotcore.md
> +Create "Things" with the AWS console for assignment to Vantiq in order to make a connection from Vantiq to AWS IoT Core's MQTT.
```suggestion
Create "Things" with the AWS console to be assigned to Vantiq in order to make a connection from Vantiq to AWS IoT Core's MQTT.    

```

2022-10-11 13:40 UTC, MasanoriKono commented on vantiq-platform-operations/readme.md
> +- [Customized configuration of deploy.yaml](./docs/eng/deploy_yaml_config.md)
```suggestion
- [Custom configuration of deploy.yaml](./docs/eng/deploy_yaml_config.md)
```

2022-10-11 13:43 UTC, MasanoriKono commented on vantiq-platform-operations/docs/eng/org_user_management.md
> +- (1) Can invite System Admin newly. Also, can invite Organization Admin newly when creating Organization.
```suggestion
- (1) Can invite System Admin newly. Also, can invite Organization Admin newly when creating an Organization.  
```

2022-10-11 13:44 UTC, MasanoriKono commented on vantiq-platform-operations/docs/eng/org_user_management.md
> +- Authorized user can be given access to the NS by sending invitation E-mail.
```suggestion
- Authorized user can grant access to the NS by sending invitation E-mail.
```

2022-10-11 13:46 UTC, MasanoriKono commented on vantiq-platform-operations/docs/eng/org_user_management.md
> +- **Home Namespace** - This is the Namespace when the user's account is created (when the user is invited to NS for the first time) and user information is managed in the Home Namespace. It cannot be
```suggestion
- **Home Namespace** - This is the Namespace where the user's account is created (when the user is invited to NS for the first time), and user information is maintained in the Home Namespace. It cannot be changed.  
```

2022-10-11 13:47 UTC, MasanoriKono commented on vantiq-platform-operations/docs/eng/org_user_management.md
> +- **Current Namespace** – The Namespace which is currently working.
```suggestion
- **Current Namespace** – The Namespace where the work is currently taking place.  
```

2022-10-11 13:48 UTC, MasanoriKono commented on vantiq-platform-operations/docs/eng/deploy_yaml_config.md
> +This article describes an example configuration that requires customization according to Private Cloud requirements. The default configuration is defined by [k8sdeploy](https://github.com/Vantiq/k8sd
```suggestion
This article describes an example configuration that requires customization according to Private Cloud requirements. The default configuration is defined by [k8sdeploy](https://github.com/Vantiq/k8sdeploy) (permission required), but the default settings are overridden in `deploy.yaml`.  
```

2022-10-11 13:50 UTC, MasanoriKono commented on vantiq-platform-operations/docs/eng/deploy_yaml_config.md
> +Use to specify a different version for a particular component in the standard configuration packaged as `vantiq_system_release`.
```suggestion
Use to specify a different version for a particular component other than the standard configuration packaged as `vantiq_system_release`.  
```

2022-10-11 13:51 UTC, MasanoriKono commented on vantiq-platform-operations/docs/eng/create_quay.io_account.md
> +Describes the procedure for creating a new account on Quay.io.
```suggestion
This article describes the procedure for creating a new account on Quay.io.  
```

2022-10-11 13:51 UTC, MasanoriKono commented on vantiq-platform-operations/docs/eng/create_quay.io_account.md
> +  It is possible to sing in to Quay.io with a RED HAT account.
```suggestion
  You can sign in to Quay.io with a RED HAT account.       
```

2022-10-11 13:53 UTC, MasanoriKono commented on vantiq-external-services-integration/docs/en/vantiq-azure-CosmosDB.md
> +In this document, describe how to do the following from Vantiq's Procedures to Cosmos DB.
```suggestion
This document describes how to do the following from Vantiq's Procedures to Cosmos DB.  

```

2022-10-11 13:56 UTC, MasanoriKono commented on vantiq-external-services-integration/docs/en/vantiq-azure-CosmosDB.md
> +It is necessary to specify an ID that does not duplicate when creating a document to CosmosDB.
```suggestion
It is necessary to specify an ID that is unique when creating a document in CosmosDB.    

```

2022-10-11 13:57 UTC, MasanoriKono commented on vantiq-external-services-integration/docs/en/vantiq-azure-CosmosDB.md
> +From Azure Portal, it is also possible to confirm that the above document is stored in the Items of the sensors container that was created.
```suggestion
From Azure Portal, it is also possible to confirm that the above document is stored in the Items of the sensors container.  

```

2022-10-11 13:58 UTC, MasanoriKono requested changes
修正お願いします。

2022-10-12 00:05 UTC, MeguShibata commented
お手数をおかけしました。修正をいたしました。

2022-10-12 00:17 UTC, MasanoriKono commented
LGTM

2022-10-12 00:17 UTC, merged