Update vantiq-install-maintenance-troubleshooting.md
fujitake/vantiq-related pull request #128
Opened 2022-11-29 05:06 UTC by wata-to

以下追加しました。

・MongoDB podが起動しない
    bootstrap init ContainerがRunningのままになる
    mongodb-2 の bootstrap init ContainerがRunningのままになる
・telegraf-ds / telegraf-promでメトリクスを収集できない
・Vantiqへの通信がタイムアウト(502/504エラー)し、keycloakのadminコンソールは正常に表示される

2022-12-01 09:13 UTC, MasanoriKono commented on vantiq-platform-operations/docs/jp/vantiq-install-maintenance-troubleshooting.md
> +
以下の点を注意点として、どこかに記載するのがよいと思いますが、いかがですか？
- Secretリソースを更新しただけだと、すでにpodにマウント済みのSecret値に反映しない。
- コンテナの起動時にのみConfig情報を読み込むケースが多い。
よって、configmapやsecretをデプロイ後、それらに依存するpodの再起動(rollout start)が必要。

2022-12-01 09:15 UTC, MasanoriKono commented on vantiq-platform-operations/docs/jp/vantiq-install-maintenance-troubleshooting.md
> +# 環境依存によるトラブル <a id="env_dependency_problem"></a>
```suggestion
# 特殊環境 (EKS, AKS以外の環境）でのトラブスシューティング事例  <a id="env_dependency_problem"></a>
```

2022-12-01 09:17 UTC, MasanoriKono commented on vantiq-platform-operations/docs/jp/vantiq-install-maintenance-troubleshooting.md
> +上記は`Kubernetesクラスタのデフォルトドメインが cluster.local ではない場合`に発生するため、デフォルトドメインを`cluster.local`にするように設定変更する必要が有る。
```suggestion
上記は`Kubernetesクラスタのデフォルトドメインが cluster.local ではない場合`ために発生した。デフォルトドメインを`cluster.local`にするように設定変更することで解消した。  
```

2022-12-01 09:18 UTC, MasanoriKono commented on vantiq-platform-operations/docs/jp/vantiq-install-maintenance-troubleshooting.md
> +上記は`MongoDBのnamespace名(Vantiqのホスト名部分)が長く、クラスタ内部DNSへのtcp通信の疎通ができない場合(udp通信は疎通可能)`に発生する可能性がある。
```suggestion
上記は当該環境で`MongoDBのnamespace名(Vantiqのホスト名部分)が長く、クラスタ内部DNSへのtcp通信の疎通ができない(udp通信は疎通可能)`ために発生した。  
```

2022-12-01 09:19 UTC, MasanoriKono commented on vantiq-platform-operations/docs/jp/vantiq-install-maintenance-troubleshooting.md
> +`クラスタ内部DNSへのtcp通信の疎通ができるようにするように設定変更` or `namespace名(Vantiqのホスト名部分)を短くする`ようにする必要が有る。
```suggestion
`クラスタ内部DNSへのtcp通信の疎通ができるようにするように設定変更` or `namespace名(Vantiqのホスト名部分)を短くする`ことで回避できる。  
```

2022-12-01 09:20 UTC, MasanoriKono commented on vantiq-platform-operations/docs/jp/vantiq-install-maintenance-troubleshooting.md
> +以下のような疎通の問題が原因で上記が発生するため、疎通できるように設定する必要が有る。
```suggestion
以下のような疎通の問題が原因で上記が発生していた。疎通できるように設定する必要が有る。  
```

2022-12-01 09:22 UTC, MasanoriKono commented on vantiq-platform-operations/docs/jp/vantiq-install-maintenance-troubleshooting.md
> +  `telegraf-prom Pod -> MongoDB,Ingress Nginx Controller`への疎通ができない
```suggestion
  `telegraf-prom Pod -> MongoDB,Ingress Nginx Controller`への疎通ができない
```
これは namespaceをまたいだ通信が出来ないことが原因で、 `telegraf-prom` をnamespaceごとにデプロイすることで解決したんでしたっけ？

2022-12-01 09:25 UTC, MasanoriKono commented on vantiq-platform-operations/docs/jp/vantiq-install-maintenance-troubleshooting.md
> +以下はKubernetesクラスタの環境が特殊であったり制限を設定していたりした場合に発生した事例。
```suggestion
以下はKubernetesクラスタの環境が特殊であったり制限を設定していたりした場合に発生した事例。
```
下の方にsharepontへのリンクがあるが、これ以降はVantiq内部用なのか、それとも詳細は隠した上で事例として解決法を説明するのか、どちらですか？ 内部用であれば敢えてこの記事に載せる必要はないのではと思います。

2022-12-01 09:26 UTC, MasanoriKono requested changes
@wata-to  確認お願いします。

2022-12-01 23:58 UTC, wata-to commented on vantiq-platform-operations/docs/jp/vantiq-install-maintenance-troubleshooting.md
> +
そうですね。追記します。

2022-12-01 23:58 UTC, wata-to commented on vantiq-platform-operations/docs/jp/vantiq-install-maintenance-troubleshooting.md
> +以下はKubernetesクラスタの環境が特殊であったり制限を設定していたりした場合に発生した事例。
内部用に近いのでこちらの記載は削除しますね。

2022-12-02 00:02 UTC, wata-to commented on vantiq-platform-operations/docs/jp/vantiq-install-maintenance-troubleshooting.md
> +  `telegraf-prom Pod -> MongoDB,Ingress Nginx Controller`への疎通ができない
そうですね。通信の制限が変更できなかったのでtelegraf-promはそれで対応しました。

2022-12-02 02:15 UTC, wata-to commented
@MasanoriKono 
修正しました。ご確認お願いします。

2022-12-02 04:55 UTC, MasanoriKono commented
LGTM

2022-12-02 04:56 UTC, merged