add article llm feature
fujitake/vantiq-related pull request #190
Opened 2023-10-05 09:44 UTC by shunsonohara

r1.37 のLLM feature を使用する手順の解説です。以下についての解説とサンプルプロジェクトを含んでいます。
- Resources
   - LLM
   - Semantic Index

 - Activity Pattern
   -  Submit Prompt
   - Answer Question

2023-10-05 12:54 UTC, fujitake commented on vantiq-apps-development/docs/jp/LLM_Platform_Support.md
line 15, 文章が途中で終わっています。使用して、の後は何かを記載しようとしたのでは？
line 17, 18, それぞれ、何をするもの、の説明を追加して欲しいです。
line 23, api keyの条件をコメントとして追記して欲しいです。モデルの利用条件を満たしたopenai api keyを手配して下さい。とか。詳細書くと、openaiの条件が変わったとき、例えばgpt-4が標準になった、とか、に書き換えが必要なので、例で書いたような記述で十分かと思います。
line 46, sentence transformers と最後にsがつきます。transformer はgoogleのオリジナルを指しており、transformersは、huggingfaceのものを指しており、これは、sentence transformersです。
line 117, Submit Prompt が単純なプロンプトに対する回答を返すアクティビティだから、ではなく、選択したモデルでは情報を有していない情報のため、適切な回答が得られません。だと思います。

2023-10-05 12:59 UTC, fujitake commented on vantiq-apps-development/docs/jp/LLM_Platform_Support.md
あと2点あります。
画像と文章の間に空行がないので、文字の横に画像が入っているケースがあります。文章の最後が消えていて、画像の左下に、最後の一部分が表示されるなど。
ちょっと瑣末なことかもですが、、Add Semantic Indexを追加する時にDefault Q&A LLMを指定しておくと、Answer Question アクティビティパターンの設定のqaLLMは指定不要ですよね。どちらかで指定しておけば、OKかと。

2023-10-06 00:28 UTC, MasanoriKono commented
@shunsonohara   Vantiq LLMを初見の人向けに冒頭で以下の説明が必要と思いました。
1.  作業フロー概念図
2.  作業フローに出てくる要素と、Vantiq のリソース名とのマッピング

1についてはこちらの資料のスライド#20-21のようなシンプルなものでよいと思います。
https://vantiq.sharepoint.com/:b:/g/ET5RvHhBfsxDuX93TJPc_IgBNn9WgY50KYRBy2xlXx5iKw?e=bq5cIQ

2023-10-06 00:34 UTC, MasanoriKono requested changes

2023-10-06 00:34 UTC, MasanoriKono commented on vantiq-apps-development/docs/jp/LLM_Platform_Support.md
> +   ![submitpromptapp_06](../../imgs/LLM_Platform_Support/submitpromptapp_06.png)
画像が間違っている

2023-10-06 00:34 UTC, MasanoriKono commented on vantiq-apps-development/docs/jp/LLM_Platform_Support.md
> +5. ログに、LLMからの回答が出力されていることを確認します。Semantic Index Entry に追加された情報から回答が生成されていることがわかります。
Semantic Indexの情報で回答していることと、情報の出典であるpdfファイルが示されていることを強調するのがよいと思います。

2023-10-10 09:01 UTC, shunsonohara commented on vantiq-apps-development/docs/jp/LLM_Platform_Support.md
> +   ![submitpromptapp_06](../../imgs/LLM_Platform_Support/submitpromptapp_06.png)
対応しました

2023-10-10 09:02 UTC, shunsonohara commented
@MasanoriKono @fujitake 
https://github.com/fujitake/vantiq-related/pull/190#issuecomment-1749829631
いったん↑以外に対応しました。

2023-10-10 10:09 UTC, fujitake approved these changes
thanks for revising.

2023-10-10 10:15 UTC, merged