Vantiqからのデータ送信方法まとめ
fujitake/vantiq-related pull request #50
Opened 2022-01-07 00:28 UTC by ykshimizu

Vantiqの各Sourceからデータを送信する際の方法、注意点をまとめたページを作成しました。

2022-01-07 01:53 UTC, MasanoriKono commented
@ykshimizu   記事のタイトルを「Vantiq Sourceを使った外部へのデータ送信のまとめ」として、「Vantiqアプリケーション開発関連」の下に入れたいです。

2022-01-07 02:00 UTC, ykshimizu commented
@MasanoriKono ページのタイトルとディレクトリを変更しました。

2022-01-07 02:01 UTC, MasanoriKono commented
PublishToSourceのアクティビティパターンで、SourceConfigを設定したスクリーンショットが欲しいです。

2022-01-07 02:03 UTC, MasanoriKono commented on vantiq-apps-development/docs/jp/data_sending.md
> +## 1. データ送信処理実装方法
1. Procedure, 2. VAILアクティビティパターン、3. Transformation + PublishToSource　とした方がわかりやすいと思います。

2022-01-07 02:05 UTC, MasanoriKono commented on vantiq-apps-development/docs/jp/data_sending.md
> +#### 2. PublishToSource Activity (+Transformation Activity)
「Transformation + PublishToSource Activity」として、詳細説明もその順番で記述する方がわかりやすいです。

2022-01-07 02:11 UTC, MasanoriKono commented on vantiq-apps-development/docs/jp/data_sending.md
> +MQTT Source自体に`Topic`、`QoS`, `Delivery Mode`の設定がございますが、これらの設定項目はデータのサブスクライブ時に使用するものであり、`送信時には使用されません`ので送信したい場合は必ず送信先のTopicを設定する必要があります。`Topic`、`QoS`,`Delivery Mode`の詳細については以下を参照してください。
```suggestion
MQTT Source自体に`Topic`、`QoS`の設定がございますが、これらの設定項目はデータのSubscribeのためのもので、`Publishでは使用されません`。`Topic`, `QoS`は送信の都度、必要です。また、`Delivery Mode`はMQTTブローカーとの通信と無関係です。`Topic`、`QoS`,`Delivery Mode`の詳細については以下を参照してください。
```

2022-01-11 04:28 UTC, ykshimizu commented
@MasanoriKono 先週いただいたフィードバック内容を反映しました。

2022-01-11 05:40 UTC, MasanoriKono commented
@ykshimizu   トップページのReadmeにもリンクを追加お願いします。

2022-01-11 06:30 UTC, MasanoriKono commented on vantiq-apps-development/docs/jp/data_sending.md
> +また、使用するSourceの種類によって、`送信したい内容部分の形式`と`送信時のコンフィグの項目`が異なります。
この部分は2. 各Source別実装サンプルに移動がよいです。

2022-01-11 06:31 UTC, MasanoriKono commented on vantiq-apps-development/docs/jp/data_sending.md
> +<th>送信したい内容部分の形式</th>
```suggestion
<th>メッセージの形式</th>
```

2022-01-11 06:32 UTC, MasanoriKono commented on vantiq-apps-development/docs/jp/data_sending.md
> +また、使用するSourceの種類によって、`送信したい内容部分の形式`と`送信時のコンフィグの項目`が異なります。
```suggestion
また、使用するSourceの種類によって、`メッセージの形式`と`送信時のコンフィグの項目`が異なります。
```

2022-01-11 06:32 UTC, MasanoriKono commented on vantiq-apps-development/docs/jp/data_sending.md
> +`PUBLISH <送信したい内容> TO SOURCE <使用するSource名> USING <送信時のコンフィグ>`
```suggestion
`PUBLISH <メッセージ> TO SOURCE <使用するSource名> USING <送信時のコンフィグ>`
```

2022-01-11 06:34 UTC, MasanoriKono commented on vantiq-apps-development/docs/jp/data_sending.md
> +Procedureで送信処理を実装する方法です。そのProcedureをAppやRuleで呼び出し、データ送信を行います。
```suggestion
実装したProcedureをAppやRuleで呼び出します。
```

2022-01-11 06:35 UTC, MasanoriKono commented on vantiq-apps-development/docs/jp/data_sending.md
> +例えば、他システムのAPIを実行してデータをPOSTする際は以下のようなProcedureを実装します。
```suggestion
例えば, Remote Sourceを用いて他システムのAPIに連携してデータをPUBLISHするProcedureは以下のようになります。
```

2022-01-11 06:36 UTC, MasanoriKono commented on vantiq-apps-development/docs/jp/data_sending.md
> +このProcedureでは`YourSource`というSourceに設定されたエンドポイントに対して引数である`event`の内容をPOSTしています。
```suggestion
このProcedureは`YourSource`というSourceに設定されたエンドポイントに対してProcedureの引数である`event`の内容をPUBLISHしています。
```

2022-01-11 06:40 UTC, MasanoriKono commented on vantiq-apps-development/docs/jp/data_sending.md
> +Procedureで送信処理を実装する方法です。そのProcedureをAppやRuleで呼び出し、データ送信を行います。
行を削除する。項の最後でも同じことを言っているので、まとめる。

2022-01-11 06:42 UTC, MasanoriKono commented on vantiq-apps-development/docs/jp/data_sending.md
> +このProcedureを`Procedure` Activityで呼び出すことでAppで使用することができます。
```suggestion
実装したProcedureをAppやRuleから呼び出します。Appからは`Procedure` Activity`を使用して呼び出します。
```

2022-01-11 06:44 UTC, MasanoriKono commented on vantiq-apps-development/docs/jp/data_sending.md
> +先ほどと同じように前のタスクの出力を、他システムへREST APIの実行によりPOSTする処理を記述する場合は以下のようになります。
```suggestion
前述のRemote Sourceを用いたデータのPUBLISHする処理を記述する場合は以下のようになります。
```

2022-01-11 06:48 UTC, MasanoriKono commented on vantiq-apps-development/docs/jp/data_sending.md
> +PublishToSource Activityの設定では以下の画像のように送信先として使用するSourceを設定します。
この部分の説明はTransformationの説明の後にする。

2022-01-11 06:53 UTC, MasanoriKono commented on vantiq-apps-development/docs/jp/data_sending.md
> +パス、ヘッダー、クエリパラメータなどコンフィグの部分はそれぞれ`Source自体に設定することができます`がリクエストの時点で上書きしたい場合などにVAIL側に記述します。
```suggestion
パス、ヘッダー、クエリパラメータなどコンフィグの部分はそれぞれ`Sourceの定義自体に設定することができます`が実行の時点で上書きしたい場合などにVAIL側に記述します。
```

2022-01-11 07:10 UTC, MasanoriKono commented on vantiq-apps-development/docs/jp/data_sending.md
> +また、REMOTE Sourceに限り`SELECT`文でPOSTすることができます。
```suggestion
また、REMOTE Sourceに限り`SELECT`文でPOSTすることができます。PUBLISH文では、返り値はリクエストが成功したかどうかがtrue/falseで返るのみなのに対し、SELECT文はレスポンスメッセージを受け取り、後続の処理でステータスコードの条件判断などに使うことができます。
```

2022-01-11 07:10 UTC, MasanoriKono commented on vantiq-apps-development/docs/jp/data_sending.md
> +PUBLISH文では、返り値はリクエストが成功したかどうかがtrue/falseで返るのみなのでレスポンスのステータスコードなどは分かりません。後続の処理でそういった内容が必要な場合はSELECT文を使用します。
この一文は削除

2022-01-11 07:11 UTC, MasanoriKono commented on vantiq-apps-development/docs/jp/data_sending.md
> +> PUBLISH文のメソッドをGETにしてリクエストをすることもできますが、返り値はtrue/falseにしかならないため、この実装をすることはほとんどありません。
この一文は削除

2022-01-11 07:16 UTC, MasanoriKono commented on vantiq-apps-development/docs/jp/data_sending.md
> +SELECT文でPOSTするProcedureをAppで呼び出して使用する場合の例は以下の通りです。
```suggestion
AppからProcedureを呼び出し、Remote SourceでPublishするまでの流れは以下のようになります。
```

2022-01-11 07:24 UTC, MasanoriKono commented on vantiq-apps-development/docs/jp/data_sending.md
> +画像右側にAppがあり、`post_data_by_proc`というタスクで`post_data` Procedureを`Procedure Activity`を使って呼び出しています。
```suggestion
1. `event`タスク（画面右側のApp）はイベントを処理し、出力を行う。
2. `post_data_by_proc`タスクは、`post_data` Procedureを`Procedure Activity`を使って呼び出す。その際、`event`タスクの出力を引数`event`として渡す。
3.  `post_data_by_proc`タスクは、SELECT文を使って外部サービスのAPIにPOSTを行う。（画面左上）
4.  `post_data_by_proc`タスクの出力として、POSTのレスポンスのメッセージが表示される。（画面左下）。 SELECT文がProcedureの最終行のため、その処理結果がProcedureの戻り値となるため。 
```

2022-01-11 07:24 UTC, MasanoriKono commented on vantiq-apps-development/docs/jp/data_sending.md
> +post_data Procedureの引数は`event`ですが、これには同Appの`event`タスクの出力が該当します。
箇条書きにまとめ

2022-01-11 07:24 UTC, MasanoriKono commented on vantiq-apps-development/docs/jp/data_sending.md
> +つまり、このAppではeventタスクの出力をPOSTしています。post_data_by_procタスクの出力（画面左下）はREST APIを実行した際のレスポンス内容が表示されています。
箇条書きに統合

2022-01-11 07:25 UTC, MasanoriKono commented on vantiq-apps-development/docs/jp/data_sending.md
> +これは、Procedureの最終行が以下のようにREST API実行時のレスポンスとなっているためです。
箇条書きに統合

2022-01-11 07:25 UTC, MasanoriKono commented on vantiq-apps-development/docs/jp/data_sending.md
> +```js
箇条書きに統合

2022-01-11 07:28 UTC, MasanoriKono requested changes
@ykshimizu  冗長に感じた文章を校正しましたので、反映お願いします。

2022-01-11 08:09 UTC, ykshimizu commented
@MasanoriKono 反映しました！

2022-01-11 08:30 UTC, MasanoriKono commented
@ykshimizu  ありがとうざいます。何度もでお手数ですが、1.3の説明内容を Transform -> PublishSourceの順番にしてほしいです。その方が他の項と内容とも整合性があって理解しやすいと思うので。

2022-01-11 09:08 UTC, ykshimizu commented
@MasanoriKono 修正しました。

2022-01-11 09:24 UTC, MasanoriKono approved these changes
LGTM

2022-01-11 09:25 UTC, merged